[credentials.users.admin]
senha = "florestamais2024"
perfil = "Admin"
nome = "Administrador"

[credentials.users.analista]
senha = "car2024"
perfil = "Analista"
nome = "Analista CAR"

[credentials.users.gestor]
senha = "pra2024"
perfil = "Gestor"
nome = "Gestor do Projeto"

[credentials.users.ipaam]
senha = "ipaam2024"
perfil = "IPAAM"
nome = "IPAAM"

[credentials.users.giz]
senha = "giz2024"
perfil = "GIZ"
nome = "GIZ"
